//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PizzaClient2.PizzaOrder {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/PizzaDAL.Entities")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<PizzaClient2.PizzaOrder.Order> OrdersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailAddress {
            get {
                return this.EmailAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailAddressField, value) != true)) {
                    this.EmailAddressField = value;
                    this.RaisePropertyChanged("EmailAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<PizzaClient2.PizzaOrder.Order> Orders {
            get {
                return this.OrdersField;
            }
            set {
                if ((object.ReferenceEquals(this.OrdersField, value) != true)) {
                    this.OrdersField = value;
                    this.RaisePropertyChanged("Orders");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Order", Namespace="http://schemas.datacontract.org/2004/07/PizzaDAL.Entities")]
    [System.SerializableAttribute()]
    public partial class Order : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<PizzaClient2.PizzaOrder.OrderedPizza> PizzasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PizzaClient2.PizzaOrder.User UserField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<PizzaClient2.PizzaOrder.OrderedPizza> Pizzas {
            get {
                return this.PizzasField;
            }
            set {
                if ((object.ReferenceEquals(this.PizzasField, value) != true)) {
                    this.PizzasField = value;
                    this.RaisePropertyChanged("Pizzas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PizzaClient2.PizzaOrder.User User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderedPizza", Namespace="http://schemas.datacontract.org/2004/07/PizzaDAL.Entities")]
    [System.SerializableAttribute()]
    public partial class OrderedPizza : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DiameterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PriceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Diameter {
            get {
                return this.DiameterField;
            }
            set {
                if ((this.DiameterField.Equals(value) != true)) {
                    this.DiameterField = value;
                    this.RaisePropertyChanged("Diameter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Pizza", Namespace="http://schemas.datacontract.org/2004/07/PizzaDAL.Entities")]
    [System.SerializableAttribute()]
    public partial class Pizza : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FamilyPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<PizzaClient2.PizzaOrder.Topping> ToppingsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FamilyPrice {
            get {
                return this.FamilyPriceField;
            }
            set {
                if ((this.FamilyPriceField.Equals(value) != true)) {
                    this.FamilyPriceField = value;
                    this.RaisePropertyChanged("FamilyPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<PizzaClient2.PizzaOrder.Topping> Toppings {
            get {
                return this.ToppingsField;
            }
            set {
                if ((object.ReferenceEquals(this.ToppingsField, value) != true)) {
                    this.ToppingsField = value;
                    this.RaisePropertyChanged("Toppings");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Topping", Namespace="http://schemas.datacontract.org/2004/07/PizzaDAL.Entities")]
    [System.SerializableAttribute()]
    public partial class Topping : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PriceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PizzaOrder.IPizzaOrder")]
    public interface IPizzaOrder {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPizzaOrder/Register", ReplyAction="http://tempuri.org/IPizzaOrder/RegisterResponse")]
        bool Register(string userName, string password, string emailAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPizzaOrder/Register", ReplyAction="http://tempuri.org/IPizzaOrder/RegisterResponse")]
        System.Threading.Tasks.Task<bool> RegisterAsync(string userName, string password, string emailAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPizzaOrder/Login", ReplyAction="http://tempuri.org/IPizzaOrder/LoginResponse")]
        System.Guid Login(PizzaClient2.PizzaOrder.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPizzaOrder/Login", ReplyAction="http://tempuri.org/IPizzaOrder/LoginResponse")]
        System.Threading.Tasks.Task<System.Guid> LoginAsync(PizzaClient2.PizzaOrder.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPizzaOrder/Logout", ReplyAction="http://tempuri.org/IPizzaOrder/LogoutResponse")]
        bool Logout(System.Guid guid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPizzaOrder/Logout", ReplyAction="http://tempuri.org/IPizzaOrder/LogoutResponse")]
        System.Threading.Tasks.Task<bool> LogoutAsync(System.Guid guid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPizzaOrder/GetAllPizzas", ReplyAction="http://tempuri.org/IPizzaOrder/GetAllPizzasResponse")]
        System.Collections.Generic.List<PizzaClient2.PizzaOrder.Pizza> GetAllPizzas(System.Guid guid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPizzaOrder/GetAllPizzas", ReplyAction="http://tempuri.org/IPizzaOrder/GetAllPizzasResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<PizzaClient2.PizzaOrder.Pizza>> GetAllPizzasAsync(System.Guid guid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPizzaOrder/GetAllToppings", ReplyAction="http://tempuri.org/IPizzaOrder/GetAllToppingsResponse")]
        System.Collections.Generic.List<PizzaClient2.PizzaOrder.Topping> GetAllToppings(System.Guid guid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPizzaOrder/GetAllToppings", ReplyAction="http://tempuri.org/IPizzaOrder/GetAllToppingsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<PizzaClient2.PizzaOrder.Topping>> GetAllToppingsAsync(System.Guid guid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPizzaOrder/GetPizzasPrice", ReplyAction="http://tempuri.org/IPizzaOrder/GetPizzasPriceResponse")]
        int GetPizzasPrice(System.Guid guid, PizzaClient2.PizzaOrder.Pizza pizza);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPizzaOrder/GetPizzasPrice", ReplyAction="http://tempuri.org/IPizzaOrder/GetPizzasPriceResponse")]
        System.Threading.Tasks.Task<int> GetPizzasPriceAsync(System.Guid guid, PizzaClient2.PizzaOrder.Pizza pizza);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPizzaOrder/ProceedOrder", ReplyAction="http://tempuri.org/IPizzaOrder/ProceedOrderResponse")]
        bool ProceedOrder(System.Guid guid, System.Collections.Generic.List<PizzaClient2.PizzaOrder.OrderedPizza> pizzas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPizzaOrder/ProceedOrder", ReplyAction="http://tempuri.org/IPizzaOrder/ProceedOrderResponse")]
        System.Threading.Tasks.Task<bool> ProceedOrderAsync(System.Guid guid, System.Collections.Generic.List<PizzaClient2.PizzaOrder.OrderedPizza> pizzas);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPizzaOrderChannel : PizzaClient2.PizzaOrder.IPizzaOrder, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PizzaOrderClient : System.ServiceModel.ClientBase<PizzaClient2.PizzaOrder.IPizzaOrder>, PizzaClient2.PizzaOrder.IPizzaOrder {
        
        public PizzaOrderClient() {
        }
        
        public PizzaOrderClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PizzaOrderClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PizzaOrderClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PizzaOrderClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Register(string userName, string password, string emailAddress) {
            return base.Channel.Register(userName, password, emailAddress);
        }
        
        public System.Threading.Tasks.Task<bool> RegisterAsync(string userName, string password, string emailAddress) {
            return base.Channel.RegisterAsync(userName, password, emailAddress);
        }
        
        public System.Guid Login(PizzaClient2.PizzaOrder.User user) {
            return base.Channel.Login(user);
        }
        
        public System.Threading.Tasks.Task<System.Guid> LoginAsync(PizzaClient2.PizzaOrder.User user) {
            return base.Channel.LoginAsync(user);
        }
        
        public bool Logout(System.Guid guid) {
            return base.Channel.Logout(guid);
        }
        
        public System.Threading.Tasks.Task<bool> LogoutAsync(System.Guid guid) {
            return base.Channel.LogoutAsync(guid);
        }
        
        public System.Collections.Generic.List<PizzaClient2.PizzaOrder.Pizza> GetAllPizzas(System.Guid guid) {
            return base.Channel.GetAllPizzas(guid);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<PizzaClient2.PizzaOrder.Pizza>> GetAllPizzasAsync(System.Guid guid) {
            return base.Channel.GetAllPizzasAsync(guid);
        }
        
        public System.Collections.Generic.List<PizzaClient2.PizzaOrder.Topping> GetAllToppings(System.Guid guid) {
            return base.Channel.GetAllToppings(guid);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<PizzaClient2.PizzaOrder.Topping>> GetAllToppingsAsync(System.Guid guid) {
            return base.Channel.GetAllToppingsAsync(guid);
        }
        
        public int GetPizzasPrice(System.Guid guid, PizzaClient2.PizzaOrder.Pizza pizza) {
            return base.Channel.GetPizzasPrice(guid, pizza);
        }
        
        public System.Threading.Tasks.Task<int> GetPizzasPriceAsync(System.Guid guid, PizzaClient2.PizzaOrder.Pizza pizza) {
            return base.Channel.GetPizzasPriceAsync(guid, pizza);
        }
        
        public bool ProceedOrder(System.Guid guid, System.Collections.Generic.List<PizzaClient2.PizzaOrder.OrderedPizza> pizzas) {
            return base.Channel.ProceedOrder(guid, pizzas);
        }
        
        public System.Threading.Tasks.Task<bool> ProceedOrderAsync(System.Guid guid, System.Collections.Generic.List<PizzaClient2.PizzaOrder.OrderedPizza> pizzas) {
            return base.Channel.ProceedOrderAsync(guid, pizzas);
        }
    }
}
